# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c50949e9f05a654cf743acf66f11c913f7e190e041486037846647535a386fa1f8c87cc7ed6817cd4dfb7cd34a080621fdb2eaa053c26473a31c8326046f5040

test:
  secret_key_base: e88259cefdbcf29083a93e3ff81c06f4c0fe683c0e27aebc8d289c0ace4b04a4f3725e6982c89868998f026a548bcd92b67f0d520f98284f33dc37f787f46cbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
